project:
  type: website
  output-dir: docs

website:
  title: "Connor Duffin"
  navbar:
    left:
      - href: index.qmd
        text: home
      - code.qmd
      - talks.qmd
  page-footer: 
    center:
      "Connor Duffin"
    right: 
      - icon: envelope 
        href: mailto:connor.p.duffin@gmail.com
      - icon: github
        href: https://github.com/connor-duffin
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true

